### ISSUE TITLE
Comparison of environments within S4 slots isn't right

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/waldo#118]
How do we make these compare equal?

```r
track <- setClass("track", slots = c(x="environment"))

e1 <- rlang::new_environment()
t1 <- track(x = e1)

e2 <- rlang::new_environment()
t2 <- track(x = e2)

all.equal(t1, t2)
#> [1] TRUE

waldo::compare(t1, t2)
#> `old@x` is <env:0x7ffd7ccfb1f8>
#> `new@x` is <env:0x7ffd7cd249d0>

waldo::compare(t1, t2, ignore_function_env = TRUE, ignore_formula_env = TRUE)
#> `old@x` is <env:0x7ffd7ccfb1f8>
#> `new@x` is <env:0x7ffd7cd249d0>
```

From slack:

> oh you can’t, because I didn’t know that all.equal ignored environments in slots
> if I’d known that I’d probably have done ignore_env = c("slot", "function", "formula"))

**Comment by hadley** [comment]
Maybe the idea in #127 resolves this because the environments would have equal values?

**Comment by hadley** [comment]
This example now works with the new compare-by-value process, so I'm going to close this issue. We can open again if the issue crops up in a different form.
