### ISSUE TITLE
Don't use format if ignore_attr = TRUE

### ISSUE THREAD

**Issue by hadley** [r-lib/waldo#134]
``` r
waldo::compare(factor("a"), 1L, ignore_attr = TRUE)
#> `old`: "a"
#> `new`: "1"
```

<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
And think through numeric comparison issues — maybe don't use format if object is numeric and tolerance is set? See terrainr failure for details.

**Comment by hadley** [comment]
But make sure this continues to fail:

```R
testthat::expect_equal(as.POSIXct("2016-07-18 16:06:06"), as.POSIXct("2016-07-18 16:06:00"))
```

**Comment by hadley** [comment]
Not sure if that should fail, because it is in within the standard numeric that tolerance that `expect_equal()` uses.

**Comment by MichaelChirico** [comment]
from ?all.equal.POSIXt

> The methods for the date-time classes by default allow a tolerance of tolerance = 0.001 seconds, and ignore scale.

**Comment by hadley** [comment]
Hmmmm, not sure how we should replicate that. Maybe it's easiest to preserve the existing (suboptimal) POSIXt behaviour for this release, and tackle in the next one?
