### ISSUE TITLE
NaN and NA compare as equal

### ISSUE THREAD

**Issue by hadley** [r-lib/waldo#150]
``` r
waldo::compare(NA_real_, NaN)
#> ✔ No differences
```

<sup>Created on 2022-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sorhawell** [comment]
I suggest this fix  #151

**Comment by bart1** [comment]
I just noticed this issue as well. The comparison being equal was somewhat unexpected
