### ISSUE TITLE
Why was the package called 'waldo'?

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/waldo#155]
Not a bug but I have trouble remembering the name of the package since I can't find a useful association. Is there a simple explanation of why it's called so (apart from the fact that there is already a package 'compare')?

**Comment by MichaelChirico** [comment]
My assumption was it's an allusion to Where's Waldo, I may be mistaken:

https://en.m.wikipedia.org/wiki/Where%27s_Wally

**Comment by GeoBosh** [comment]
Thanks, sounds plausible.
