### ISSUE TITLE
Change default "old", "new" in waldo::compare print to "x", "y"

### ISSUE THREAD

**Issue by schmitzi89** [r-lib/waldo#158]
Currently, if the user provides two R objects to the x and y parameters of waldo::compare, their respective differences get printed as "old" and "new". It would be more consistent, if the differences get printed as "x" and "y" per default.

I know its a detail but I found myself manually checking it multiple times already.

**Comment by DanChaltiel** [comment]
@schmitzi89 you can use `x_arg` and `y_arg` to chang this.

However, it would be very nice if `compare()` used something like `checkmate::vname()` to infer the name.

Here is the replacement that I use: 

``` r
library(tidyverse)
iris_2 = iris
iris_2[1,1] = 99

vname = function (x) {
  paste0(deparse(eval.parent(substitute(substitute(x))), width.cutoff=500L), collapse="\n")
}

compare2 = function (x, y, x_arg=vname(x), y_arg=vname(y), ...) {
  waldo::compare(x, y, x_arg=x_arg, y_arg=y_arg, ...)
}

compare2(iris, iris_2)
#> iris vs iris_2
#>                 Sepal.Length
#> - iris[1, ]              5.1
#> + iris_2[1, ]           99.0
#>   iris[2, ]              4.9
#>   iris[3, ]              4.7
#>   iris[4, ]              4.6
#> 
#>   `iris$Sepal.Length[1:4]`:  5 5 5 5
#> `iris_2$Sepal.Length[1:4]`: 99 5 5 5
```

<sup>Created on 2023-02-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
We could use `rlang::caller_arg()` here

**Comment by hadley** [comment]
But actually I don't think that's what you want because when you type `waldo::compare(foo, 100)` you don't want to use the names of the arguments.

**Comment by DanChaltiel** [comment]
@hadley I'm not sure why anyone would ever write `waldo::compare(foo, 100)` or something similar. I would think `waldo` is meant for complex objects so hardcoding an expression seems rather awkward to me.

But even so, I think that using names here is natural and expected: 
```r
compare2(iris, 100)
# `iris` is an S3 object of class <data.frame>, a list
# `100` is a double vector (100)
```
