### ISSUE TITLE
Better comparison for bit64 and numeric

### ISSUE THREAD

**Issue by mgirlich** [r-lib/waldo#159]
``` r
testthat::expect_equal(
  tibble::tibble(x = bit64::as.integer64(1)),
  tibble::tibble(x = 1)
)
```

produces

```
Error:
! tibble::tibble(x = bit64::as.integer64(1)) (`actual`) not equal to tibble::tibble(x = 1) (`expected`).

`class(actual$x)` is a character vector ('integer64')
`class(expected$x)` is absent

  `unclass(actual$x)`: 0
`unclass(expected$x)`: 1
```

It would be nicer if big ints could be treated like integers where possible.

**Comment by hadley** [comment]
I'm preparing for a waldo release, so if you have specific ideas on what this should look like, I might be able to squeeze it in.

**Comment by mgirlich** [comment]
It would be nice if it had the same behaviour as for integer and double comparison:

``` r
testthat::expect_equal(
  tibble::tibble(x = 1L),
  tibble::tibble(x = 1)
)
```

<sup>Created on 2023-04-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Minimal reprex:

``` r
one <- bit64::as.integer64(1)
tol <- testthat::testthat_tolerance()

waldo::compare(1L, 1, tolerance = tol)
#> ✔ No differences
waldo::compare(1L, one, tolerance = tol)
#> `class(old)` is absent
#> `class(new)` is a character vector ('integer64')
#> 
#> `old`: 1
#> `new`: 0
waldo::compare(1, one, tolerance = tol)
#> `class(old)` is absent
#> `class(new)` is a character vector ('integer64')
#> 
#> `old`: 1
#> `new`: 0
```

<sup>Created on 2023-08-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
This is going to require some fairly deep changes to be able to ignore the varying class attribute; there's a pretty strong assumption of atomic vector-ness in waldo.
