### ISSUE TITLE
Equivalent environments are seen as different when named

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/waldo#161]
``` r
e1 <- new.env()
e2 <- new.env()
attr(e1, "foo") <- attr(e2, "foo") <- "foo_"
waldo::compare(e1, e2)
#> ✔ No differences

attr(e1, "name") <- attr(e2, "name") <- "name_"
waldo::compare(e1, e2)
#> `old` is <env:name_>
#> `new` is <env:name_>
```

<sup>Created on 2023-03-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Named environments are deliberately compared by reference as of #133. I made that change as part of https://github.com/r-lib/waldo/issues/127#issuecomment-1063488933 — waldo compares generally compares environments by values but it compare named environments by reference because these are usually special environments (i.e. empty/base/global and packages environments). 

Can you please explain where you saw this problem?

**Comment by moodymudskipper** [comment]
Sure, it did happen in artificial cases as you expected.

The package [{constructive}](https://github.com/cynkra/constructive) prints idiomatic building code from objects, this includes environments with all the caveats that this entails. It uses Waldo to confirm that the generated code is faithful to the object.

``` r
# devtools::install_github("cynkra/constructive")
library(constructive)
e1 <- new.env()
e1$x <- 1
attr(e1, "name") <- "my_env"

# identical but uninteresting
construct(e1)
#> constructive::env("0x11bd168a0", parents = "global")

# not identical but equivalent, and interesting 
construct(e1, opts_environment("list2env"), check = TRUE)
#> list2env(list(x = 1), parent = .GlobalEnv) |>
#>   structure(name = "my_env")
#> Error in `check_round_trip()`:
#> ! {constructive} couldn't create code that reproduces perfectly the input
#> `original` is <env:my_env>
#> `recreated` is <env:my_env>
```

<sup>Created on 2023-04-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It's important for {constructive} not to choke even on rare cases because we'd like the package to be a robust tool to investigate corrupt or weird objects. 

You mentioned already in #152 that you expect regular objects in waldo so this issue might be out of scope. In this case I might be able to special case this with a `compare_proxy.environment` method defined locally with `rlang::local_bindings(.env = .GlobalEnv)`

**Comment by hadley** [comment]
I'm going to close this issue because I think it is out of scope, and it sounds like you have a work around.
