### ISSUE TITLE
[enhancement] return differences in objects as R code that can be used to document & reproduce changes in DF

### ISSUE THREAD

**Issue by SugarRayLua** [r-lib/waldo#198]
Thanks for the very useful package!

It would be additionally helpful in there could be an option in waldo that would allow the result of a comparison to be returned in terms of R script code that be used to recreate the actual changes that have been made to a dataframe. That way if needed a R user could make a particular sporadic change to a dataframe, document the result of that change to the dataframe, and then use the returned R script to reproduce the change in the dataframe. 

Please see the example that one developer is currently working on to accomplish this result independent of the Waldo package:

Example of a returned R script result documenting the new dataframe's cell changes after comparing two data frames:

dat[3, 1] <- 0.1
dat[2, 2] <- 5
dat[1, 3] <- FALSE
dat[3, 4] <- "E"
levels(dat[, 5]) <- c(levels(dat[, 5]), "5")
dat[3, 5] <- "5"
levels(dat[, 6]) <- c(levels(dat[, 6]), "E")
dat[1, 6] <- "E"

(Please see the complete package description at:
https://github.com/matt-dray/tide)

Potentially such a feature would be most useful when added to the DataEditR package:
https://dillonhammill.github.io/DataEditR/

(DataEditR currently includes a feature to export an R script to reproduce the entire changed dataframe but often all that would be needed [and which would be more concise] would be to only generate the R script needed to generate the change in the cells of the dataframe as the tide developer noted above is attempting to accomplish)

Thank you for considering this enhancement.

**Comment by hadley** [comment]
That's a great idea, and  would be super useful, but it would be a considerable increase in scope for waldo. So I think it would be better off in another package.

**Comment by MichaelChirico** [comment]
@SugarRayLua one such package is {constructive}:

https://github.com/cynkra/constructive
