### ISSUE TITLE
compare can't handle externalptr

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/waldo#22]
Don't think you need `arrow` for this but it was a quick way to get an externalptr.

```r
library(arrow)
library(waldo)
a <- Array$create(1)
b <- Array$create(2)
compare(a, b)

## Error: x$.:xp:.: unsupported type externalptr
```

**Comment by hadley** [comment]
Now I get:

```
`x$.:xp:.` is <pointer: 0x7f82957c5f50>
`y$.:xp:.` is <pointer: 0x7f82754964d0>
```

which is obviously not much better, but at least shows something.

What should happen here? I assume you really want to register some method that allows you to call your own C code to do the comparison?

**Comment by nealrichardson** [comment]
Currently we have https://github.com/apache/arrow/blob/master/r/R/arrow-package.R#L111-L113

```r
all.equal.ArrowObject <- function(target, current, ..., check.attributes = TRUE) {
  target$Equals(current, check_metadata = check.attributes)
}
```

which, you're right, delegates to the C++ library the equality check (and handles the difference between `expect_equal()` and `expect_equivalent()`). 

Some way to register methods would be nice, though I suppose we could hack around it something like this in a `helper.R` file:

```r
expect_equal <- function(actual, expected, ...) {
  if (inherits(expected, "ArrowObject")) {
    do_old_expect_equal(actual, expected, ...)
  } else {
    testthat::expect_equal(actual, expected, ...)
  }
}
```

**Comment by hadley** [comment]
I'd like to see a few more use cases before I commit to a generic, so I think your `expect_equal()` hack is a good approach in the near future.

**Comment by nealrichardson** [comment]
Yep, makes sense 👍

**Comment by hadley** [comment]
The most common place where this is going to come up is data.table

**Comment by hadley** [comment]
I've added experimental proxy methods for xml2 and data.table; if this approach has legs, then these methods should be defined conditionally, so package authors retain control.
