### ISSUE TITLE
allow for named lists inside waldo::compare

### ISSUE THREAD

**Issue by njtierney** [r-lib/waldo#35]
I was using `bench::mark` and wanted to explore where some differences were in the outputs, and thought I could just paste the named output into `waldo`, but it requires no named input. Just thought this might be a nice feature that makes it a bit more consistent, perhaps?

Here's a reprex of what I mean:

``` r
# benchmark allows for using named elements
bm_colsums <- 
  bench::mark(
    original = sum(is.na(airquality)) / length(is.na(airquality)),
    improved = mean(is.na(airquality))
  )

# I'd like to be bale to pass the same inputs into waldo, but it requies no
# names
waldo::compare(original = sum(is.na(airquality)) / length(is.na(airquality)),
               improved = mean(is.na(airquality)))
#> Error in waldo::compare(original = sum(is.na(airquality))/length(is.na(airquality)), : unused arguments (original = sum(is.na(airquality))/length(is.na(airquality)), improved = mean(is.na(airquality)))

waldo::compare(sum(is.na(airquality)) / length(is.na(airquality)),
               mean(is.na(airquality)))
#> ✓ No differences
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Those aren't names in the output, but function argument names?

**Comment by njtierney** [comment]
I think I can do a better job explaining what I mean. 

I guess my thought was that one of the things I really like in `bench::mark` is that I can provide the named inputs like so:

``` r
# benchmark allows for using named elements
bm_colsums <- 
  bench::mark(
    original = 1 + 1,
    improved = sum(1, 1, 1)
  )
#> Error: Each result must equal the first result:
#> `original` does not equal `improved`
```

But then if I want to evaluate why this was different (in this small example), I would be tempted to chuck these named inputs into `waldo::compare`:

``` r
# I'd like to be bale to pass the same inputs into waldo like so:
waldo::compare(original = 1 + 1,
               improved = sum(1, 1, 1))
#> Error in waldo::compare(original = 1 + 1, improved = sum(1, 1, 1)): unused arguments (original = 1 + 1, improved = sum(1, 1, 1))
```

This doesn't work, because `compare` takes arguments `x` and `y`, and the equivalent is:

``` r
# but the equivalent is
waldo::compare(x = 1 + 1,
               y = sum(1, 1, 1),
               x_arg = "original",
               y_arg = "improved")
#> `original`: 2
#> `improved`: 3
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I guess I just noticed that this was a case where I expected `waldo::compare` to behave similarly to `bench::mark`, in terms of its input, and there was friction in moving between the two to find where there was a difference in the inputs.

That said, I can appreciate that `waldo::compare` is only designed to take two inputs, so using dots to capture the input might be challenging.

**Comment by hadley** [comment]
Maybe waldo should get a `compare_all()` function?

**Comment by njtierney** [comment]
Yeah that sounds awesome!

**Comment by hadley** [comment]
Looking at this again, it looks mostly specific to bench, so I think we can just fix there: https://github.com/r-lib/bench/issues/92
