### ISSUE TITLE
Output incorrect in terminal, correct in RStudio

### ISSUE THREAD

**Issue by jcheng5** [r-lib/waldo#42]
Data (two .rda files) (may require `sp` package):
[example.zip](https://github.com/r-lib/waldo/files/5119475/example.zip)

Code:

```r
load("new.rda")
atlStorms2005_new <- atlStorms2005
load("old.rda")
waldo::compare(atlStorms2005, atlStorms2005_new)
```

In RStudio, I get these (correct) results:

```
`x@proj4string@projargs`: "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
`y@proj4string@projargs`: "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"                     
```

At the terminal (Mac, R 3.6.1), I get:
```
x@proj4string@projargs vs y@proj4string@projargs
+ "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
- "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
```

The `+` and `-` signs appear to be reversed.

**Comment by gaborcsardi** [comment]
I think the output is different because the width on the console is different. 

IDK if the `+` and `-` signs are reversed, it seems that the convention is that `y` is "old":

```r
> x <- strrep("x-", 30)
> waldo::compare(rep(x,10), c(x, "bah", rep(x,10)))
x[1:4] vs y[1:5]
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
- "bah"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"

x[8:10] vs y[9:12]
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
  "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
- "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-"
```

**Comment by jcheng5** [comment]
Oh, thanks, you're totally right. That's very very surprising to me, but it's right there in the docs, "y is treated as the reference object so messages describe how x is different to y". I can see also how this matches the testthat expectation style, it's just very surprising from the pov of using "diff".

**Comment by gaborcsardi** [comment]
Yeah, it trips me up as well. At this point it is what it is I guess....

**Comment by hadley** [comment]
We can change anything 😄

**Comment by hadley** [comment]
(Nothing uses waldo apart from testthat, so now is the time to make the change if you think it's the wrong way around)

**Comment by jcheng5** [comment]
Or add `waldo::diff(old, new)`?

**Comment by hadley** [comment]
Yeah, I like the idea of `diff()` — and maybe it could use substitute to automatically pull out the names of the things you're comparing.

**Comment by hadley** [comment]
Does this seem right?

```R
old <- list(1, 2:10, "x")
new <- list(1, 2:11, "x")
diff(old, new)
#>  `old[[2]][7:9]`: 8 9 10   
#> `new[[2]][7:10]`: 8 9 10 11
```

**Comment by jcheng5** [comment]
Personally, I think I prefer hardcoded "old" and "new" as the labels (regardless of the names coming in). But either way, I like it!

**Comment by hadley** [comment]
Well that's even easier 😄

**Comment by jcheng5** [comment]
Looks great, thanks!

**Comment by hadley** [comment]
Just to close the loop on this — I completely misdiagnosed the problem and then developed a very suboptimal solution. The real problem + solution is in #44
