### ISSUE TITLE
Minimum testthat should be 3.0.0

### ISSUE THREAD

**Issue by QuLogic** [r-lib/waldo#55]
In Fedora, we don't have `testthat` 3.0.0 in anything but Rawhide, and since `waldo` doesn't specify a version, I built it in 33&32. However, these [failed](https://koji.fedoraproject.org/koji/taskinfo?taskID=55304951) due to missing `expect_snapshot`. As this appears to come from `testthat` 3.0.0, the `DESCRIPTION` should list that, unless there's some way to avoid using those.

**Comment by hadley** [comment]
Sure. Want to do a PR?

**Comment by QuLogic** [comment]
Ah sorry, I meant to come back and do so, but it slipped my mind.
