### ISSUE TITLE
Feature idea: compare whole sets

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/waldo#61]
First of all, I want to say how much I love this package, it makes debugging and data-peeking so much easier, so thanks a lot.

Another need I frequently encounter during those processes is the comparison of 2 unordered sets: I'd like to know which values of A are in B and which values of B are in A. This is particularly useful before joining tables.

I made a little **draft** function for this, it only outputs the ratio of missings and lacks all those fancy waldo features: 
``` r
library(tidyverse)
library(glue)
compare_set = function(x, y){
  xiny = (x %in% y) %>% sum(na.rm = T)
  xinypercent = (x %in% y) %>% mean(na.rm = T) %>% scales::percent()
  yinx = (y %in% x) %>% sum(na.rm = T)
  yinxpercent = (y %in% x) %>% mean(na.rm = T) %>% scales::percent()
  rtn = c(
    glue("x in y = {round(xiny, 2)} / {length(x)} ({xinypercent})"),
    glue("y in x = {round(yinx, 2)} / {length(y)} ({yinxpercent})")
  )
  cat(rtn[1], "\n")
  cat(rtn[2])
  invisible(rtn)
}
a=1:20
b=10:50
compare_set(a,b)
#> x in y = 11 / 20 (55%) 
#> y in x = 11 / 41 (27%)
```

<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With some more insight in the output (for instance which value is missing from `a` or `b`), I think it would totally fits the scope of the waldo package: find the needle in the haystack.

**Comment by DanChaltiel** [comment]
Using `unique` and `sort` might be a way to have a nice output:

``` r
a=1:20
b=10:50
compare_set2 = function(x, y, ...) waldo::compare(unique(sort(a)), unique(sort(b)), ...)
compare_set2(a,b)
#> `old[1:12]`: 1 2 3 4 5 6 7 8 9 10 and 2 more...
#>  `new[1:3]`:                   10           ...
#> 
#> `old[18:20]`: 18 19 20                      and 23 more...
#>  `new[9:41]`: 18 19 20 21 22 23 24 25 26 27            ...
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I don't think this would work in waldo because there's no obvious way to specify when this behaviour would be used — it seems unlikely that you'd want to recursively apply it to every pair of vectors being compared, so you'd need some way to describe exactly where you want to use it.  Or if you only wanted to apply it to the top level, you can already use your approach of calling `sort()` (and possibly `unique()`).
