### ISSUE TITLE
Unclear error message [misuse]

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/waldo#62]
I'm trying to compare some tibbles of different dimensions to find which rows are missing from one another (see https://github.com/r-lib/waldo/issues/61).

Before I could understand that `waldo::compare()` was definitely not the right tool, I tried it and got the weirdest error message ever:

``` r
a=1:20
b=10:500
waldo::compare(a, b)
#> Error in diff_myers(args[["a"]], args[["b"]], max.diffs = args[["max.diffs"]], : 
#>   Logic Error: Exceeded buffer for finding fake snake; contact maintainer.
```
<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that `waldo::compare(1:20, 10:50)` does not throw this error.

This might pertain to https://github.com/brodieG/diffobj/blob/master/src/diff.c as it is the only occurrence of the message I could find on google.

Even if this is utterly not a valid use case of this package, I thought you might want to know it can happen, perhaps to address the case with a better message.

**Comment by hadley** [comment]
Hmm, I see a slightly different error:

``` r
a <- 1:20
b <- 10:500
waldo::compare(a, b)
#> Error in diff_myers(args[["a"]], args[["b"]], max.diffs = args[["max.diffs"]], : Internal Error: reached theoretically unreachable branch 2, contact maintainer.
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

But it's coming straight from diffobj, so I'll file an error there:

``` r
a <- 1:20
b <- 10:500

diffobj::ses(a, b, max.diffs = 100)
#> Error in diff_myers(args[["a"]], args[["b"]], max.diffs = args[["max.diffs"]], : Internal Error: reached theoretically unreachable branch 2, contact maintainer.
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by brodieG** [comment]
@DanChaltiel if you are still able to reproduce your specific error message (as opposed to @hadley's), it would help me if you could run the following on your system:

```
a=1:20
b=10:500
trace(diffobj::ses, quote({str(a); str(b); str(max.diffs)}))
waldo::compare(a, b)
untrace(diffobj::ses)
sessionInfo()
```

**Comment by DanChaltiel** [comment]
@brodieG Actually, and it is very surprising since I didn't update anything, I cannot reproduce my error and I end up getting Hadley's.
