### ISSUE TITLE
diff_element() should probably call enc2utf8() before encodeString()

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/waldo#66]
In R-devel, there have been some recent changes to how encodings are handled. I am not entirely sure what changed, but it cause vctrs to fail on this one build. Notably, this build uses the ISO8859-15 charset rather than UTF-8.

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/vctrs-00check.html

Using the rhub docker image with `rhub::local_check_linux(image = "rhub/debian-clang-devel")`, I was able to reproduce the above two issues, but it looks a little different (The A and degree mark disappear here? I imagine it is still the same issue, just printing differently).

```r
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  `actual` (vec_unique(x)) not identical to `expected` (`expect`).
  
  `attr(actual[[2]], 'enc2')[[1]]`:   "°C"
  `attr(expected[[2]], 'enc2')[[1]]`: "C" 
  
  `attr(actual[[2]], 'enc3')`:   "°C"
  `attr(expected[[2]], 'enc3')`: "C" 
  Backtrace:
      x
   1. \-vctrs:::expect_identical(vec_unique(x), expect) test-translate.R:126:2
   2.   \-vctrs:::expect_waldo_equal("identical", act, exp, info, ...) helper-vctrs.R:55:2
  
  [ FAIL 2 | WARN 0 | SKIP 35 | PASS 4099 ]
```

I believe that I have tracked this down to a change in `expect_identical()` when waldo is used. When I switch to using the old version of `expect_identical()` that doesn't use waldo, the tests that fail here pass again.

`diff_element()` calls `encodeString()` here:
https://github.com/r-lib/waldo/blob/a083b8380a33f00748f0ac1666158c609f52ab85/R/diff.R#L91

Then in `ses()`, `enc2utf8()` is called:
https://github.com/r-lib/waldo/blob/a083b8380a33f00748f0ac1666158c609f52ab85/R/ses.R#L10-L13

I believe the ordering here is what is breaking this test.

On the above mentioned `"rhub/debian-clang-devel"` docker image, I get the following output. Note that this image is specifically designed to _not_ support UTF-8 (AFAIK).

```r
utf8 <- "\u00B0C"

# No UTF-8 support
utf8
#> [1] "?C"
# But marked as UTF-8
Encoding(utf8)
#> [1] "UTF-8"

# There is latin1 support here
latin1 <- iconv(utf8, from = "UTF-8", to = "latin1")

latin1
#> [1] "°C"
Encoding(latin1)
#> [1] "latin1"

# These strings are considered identical
identical(utf8, latin1)
#> [1] TRUE

# If we wanted to compare these strings with `expect_identical()`:
# Waldo first calls encodeString(), then does enc2utf8()
# Note that encodeString() loses the marked encoding (it becomes native, i think)
utf8_quote <- encodeString(utf8, quote = "\"")
latin1_quote <- encodeString(latin1, quote = "\"")

utf8_quote
#> [1] "\"?C\""
Encoding(utf8_quote)
#> [1] "UTF-8"

latin1_quote
#> [1] "\"°C\""
Encoding(latin1_quote)
#> [1] "unknown"

# now we try and use enc2utf8() on these as waldo does
utf8_enc <- enc2utf8(utf8_quote)
latin1_enc <- enc2utf8(latin1_quote)

utf8_enc
#> [1] "\"?C\""
Encoding(utf8_enc)
#> [1] "UTF-8"

latin1_enc
#> [1] "\"°C\""
Encoding(latin1_enc)
#> [1] "UTF-8"

# so by the time waldo actually compares them, they look different
identical(utf8_enc, latin1_enc)
#> [1] FALSE
```

If the strings are first converted to UTF-8 with `enc2utf8()`, then `encodeString()` is called, they will remain identical.

**Comment by hadley** [comment]
Sounds reasonable. Want to do a PR?

**Comment by jimhester** [comment]
If you want to check with a non-UTF-8 locale on GitHub Actions you can do it like this

https://github.com/r-lib/fs/commit/b258f94c13cdcd82bf401cb4c90ce7a12d02c82a#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310
