### ISSUE TITLE
Suggestion:  indicate use of proxy in output

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/waldo#73]
I'm updating `rgl`, and have changed the internal layout of some objects.  I have an `all.equal()` method for these objects that knows to ignore the irrelevant changes, but `testthat::expect_equal()` doesn't use that.  That's a bit irritating, but I can work around it by adding a `compare_proxy` method that canonicalizes objects.  However, output is now slightly misleading.  For example, if I have two objects with components in a different order, the report doesn't reflect that:

``` r
library(rgl)
x <- cube3d()
names(x)
#> [1] "vb"        "material"  "normals"   "texcoords" "ib"
y <- x
y$vb2 <- y$vb
y$vb <- NULL
waldo::compare(x, y)
#> `names(old)`: "ib" "material" "vb" 
#> `names(new)`: "ib" "material" "vb2"
#> 
#> `old$vb` is a double vector (-1, -1, -1, 1, 1, ...)
#> `new$vb` is absent
#> 
#> `old$vb2` is absent
#> `new$vb2` is a double vector (-1, -1, -1, 1, 1, ...)
```

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Notice that the names of `x` don't match `names(old)`, because we're really looking at `compare_proxy(x)`.

I think it would be sufficient to add something like:

    Using proxies for comparison:

at the start.

**Comment by hadley** [comment]
The problem is that the proxy might appear at any level in the tree, and we'd need to think about the display when there are no differences.

But is this still needed, or do you think it's is mostly solved by the ability to add comparison options as attributes in #75?

**Comment by dmurdoch** [comment]
I'd say it's not very important. 

I don't think I looked into what the implementation would be like, but maybe a solution would be to set a flag when  `compare_proxy` is used, and then at the end print `Note:  used proxies for comparison.` Not sure how easy that would be to do automatically, so maybe it would have to be optional:  a `compare_proxy` method could optionally set some global flag to say the note should be printed.
