### ISSUE TITLE
using ignore_attr with character vector has no effect on result

### ISSUE THREAD

**Issue by tmwdr** [r-lib/waldo#74]
Dear Hadley

Thank you very much for the fantastic {waldo} package, it is very useful to compare complex list-objects!

I have a question regarding the use of the `ignore_attr` argument. I would like to exclude the named list-element "c" from the comparison. Am I using the parameter correct or did I maybe misunderstand its use?

``` r
library(waldo)

# value of $c differs
x <- list(a = 1, b = 2, c = 3)
y <- list(a = 1, b = 2, c = 4)

# actual result
compare(x, y, ignore_attr = c("c"))
#> `old$c`: 3
#> `new$c`: 4

# expected result (adhoc solution: drop list-element "$c" before calling `compare`)
compare(x[c("a", "b")], y[c("a", "b")])
#> ✓ No differences
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thank you!

**Comment by hadley** [comment]
Those lists don't have any attributes:

``` r
library(waldo)

x <- 1
attributes(x) <- list(a = 1, b = 2, c = 3)
y <- 1
attributes(y) <- list(a = 1, b = 2, c = 4)

compare(x, y)
#> `attr(old, 'c')`: 3
#> `attr(new, 'c')`: 4
compare(x, y, ignore_attr = "c")
#> ✓ No differences
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tmwdr** [comment]
Thank you for the clarification! 🙏🏻
