### ISSUE TITLE
Support waldo comparisons of RProtoBuf objects

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/waldo#81]
Hi team!

RProtoBuf objects are like XML objects, in that they tend to store a pointer along with a few pieces of string information about the object:
https://github.com/eddelbuettel/rprotobuf/blob/5615e9483b0c443fbd5774df05b8fa4e53cfb0b7/R/00classes.R#L20

Since all protobuf objects have a well-defined string representation, I believe that using obj$toString() would be a suitable proxy.
https://googleapis.dev/python/protobuf/latest/google/protobuf/text_format.html

I'm not sure of the best location for adding these methods. This seems like a missing part of the RProtoBuf API, but it would be nice to avoid adding the waldo dependency to that package.
https://github.com/eddelbuettel/rprotobuf/issues/78

Would it be possible to add them here?

**Comment by hadley** [comment]
Sure. In general, I think it's better to live in the package that defines the object, but if the maintainer of that package doesn't use testthat it's often hard to motivate them, so it's fine to live here.
