### ISSUE TITLE
Should num_equal() depend on sign?

### ISSUE THREAD

**Issue by torockel** [r-lib/waldo#9]
Hi Hadley,
I find your idea for a new package for finding difference interesting. By chance, I saw that `num_equal()` sometimes depends on the sign of `y` (through `avg_y`):
``` r
num_equal(4, 4 + 2 * .Machine$double.eps ^ 0.5)
#> [1] TRUE
num_equal(-4, -4 + 2 * .Machine$double.eps ^ 0.5)
#> [1] FALSE
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Is this behaviour intended?

**Comment by hadley** [comment]
I think you missed a minus sign?

``` r
waldo:::num_equal(4, 4 + 2 * .Machine$double.eps ^ 0.5)
#> [1] TRUE
waldo:::num_equal(-4, -4 - 2 * .Machine$double.eps ^ 0.5)
#> [1] FALSE
```

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
No, that doesn't explain it (did I even look at my own reprex?)

``` r

waldo:::num_equal(4, 4 - 2 * .Machine$double.eps ^ 0.5)
#> [1] TRUE
waldo:::num_equal(4, 4 + 2 * .Machine$double.eps ^ 0.5)
#> [1] TRUE

waldo:::num_equal(-4, -4 - 2 * .Machine$double.eps ^ 0.5)
#> [1] FALSE
waldo:::num_equal(-4, -4 + 2 * .Machine$double.eps ^ 0.5)
#> [1] FALSE
```

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
