### ISSUE TITLE
Confusing output after replacing values

### ISSUE THREAD

**Issue by ericnewkirk** [r-lib/waldo#96]
I noticed this when replacing a subset of the values in one column with values from another. `compare` often represented those differences as an insertion in one spot and a deletion at another, rather than as a simple replacement. This only happened when there were adjacent matching values in the comparison and multiple replacements near each other.

```r
old <- rep("aaaaaaaaaaaa", 10)
new <- replace(old, c(4, 6), "bbbbbbbbbbbb")
waldo::compare(old, new)

#     old            | new               
# [1] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [1]
# [2] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [2]
# [3] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [3]
# [4] "aaaaaaaaaaaa" - "bbbbbbbbbbbb" [4]
# [5] "aaaaaaaaaaaa" -                   
# [6] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [5]
#                    - "bbbbbbbbbbbb" [6]
# [7] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [7]
# [8] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [8]
# [9] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [9]
```

Instead of indicating that elements 4 and 6 were changed in the above, `compare` suggests that `old[4:5]` were replaced with `new[4]`, and a new element was added between `old[6]` and `old[7]`. It seems to prioritize the fact that `new[5]` matches `old[6]` over the match at element 5 in both. I'm not sure it really matters, but it seemed like an odd way to interpret/describe that difference.

**Comment by hadley** [comment]
With the dev version I see

```R
    old            | new               
[1] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [1]
[2] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [2]
[3] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [3]
[4] "aaaaaaaaaaaa" - "bbbbbbbbbbbb" [4]
[5] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [5]
[6] "aaaaaaaaaaaa" - "bbbbbbbbbbbb" [6]
[7] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [7]
[8] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [8]
[9] "aaaaaaaaaaaa" | "aaaaaaaaaaaa" [9]
```

So this case is already fixed, but only because I now pick the smallest of a "smart" diff and a line-by-line diff. Unfortunately, I otherwise have little control over how the diff algorithm works.

**Comment by ericnewkirk** [comment]
Thanks for following up - glad it won't be an issue in the future. Your output is exactly what I was expecting.
